

<script defer src="<?php echo $iniObj->UIPath; ?>/js/jquery.dataTables.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/select2.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/dataTables.responsive.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/main.js"></script>

</body>

<!-- Mirrored from live.envalab.com/html/envotek/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 26 May 2021 14:19:50 GMT -->
</html>