<!DOCTYPE html>
<html lang="en">


<head>
	<meta charset="utf-8">
	<title>GEMO - Gestion des Marchands Opérateurs</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<meta name="keywords" content="gemo">
	<meta name="description" content="GEMO - Gestion des Marchands Opérateurs">
	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&amp;display=swap" rel="stylesheet">
	<!-- Favicon -->
	<link rel="icon" type="image/png" href="<?php echo $iniObj->UIPath; ?>/img/favicon.png">
	<!-- Bootstrap Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/bootstrap.min.css">
	<!-- Font Awesome Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/font-awesome.min.css">
	<!-- IcoFont Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/icofont.min.css">
	<!-- IcoMoon Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/themify-icons.css">
	<!-- Magnific Popup Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/magnific-popup.css">
	<!-- Owl Carousel Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/owl.carousel.min.css">
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/owl.theme.default.min.css">
	<!-- Site Main Style sheet css -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/styles.css">
	<!-- Site Main Responsive CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/responsive.css">
</head>

<body>

	<!-- Start Preloader Area -->
    <div id="loader">
        <div class="spinner">
            <div class="dot1"></div>
            <div class="dot2"></div>
        </div>
    </div>
	<!-- End Preloader Area -->
	
	<!-- Start Navbar Area-->
	<nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">
		<div class="container"> <a class="navbar-brand js-scroll" href="index-2.html">
			<div style="width:150px" id="black">
				<img src="<?php echo $iniObj->UIPath; ?>/logo" alt="Logo GEMO" srcset="">
			</div>
			<div style="width:250px" id="ligth">
				<img src="<?php echo $iniObj->UIPath; ?>/logo_light" alt="Logo GEMO" srcset="">
			</div> </a>
			<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault" aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation"> <span></span>
				<span></span>
				<span></span>
			</button>
			<div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
				<ul class="navbar-nav">
					<li class="nav-item"> <a class="nav-link js-scroll active" href="#home">Home</a>
					</li>
					<li class="nav-item"> <a class="nav-link js-scroll" href="#features">Fonctionnalités</a>
					</li>
					<li class="nav-item"> <a class="nav-link js-scroll" href="#review">Review</a>
					</li>
					<li class="nav-item"> <a class="nav-link js-scroll" href="#contact">Contact</a>
					</li>
					<li class="nav-item"> <a class="nav-link js-scroll" href="<?php $lib->customerSite ?>/connecter">Se connecter</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<!-- End Navbar Area -->
	
	<!-- Start Home Section -->
	<header id="home" class="home-area hero-equal-height section-padding overflow-hidden d-flex align-items-center">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-12 col-md-7 col-lg-6">
					<div class="text-left home-content z-index position-relative">
						<h1>Premium Startup & App Landing Page</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a href="#0" class="button home-btn-1">Free Download App</a>
						<a href="#about" class="button home-btn-2 js-scroll">More Info</a>
					</div>
				</div>
				<div class="col-12 col-md-5 col-lg-6">
					<div style="position:absolute;z-index: 50;right: 20px;">
						<img src="<?php echo $iniObj->UIPath; ?>/img/hero-mockup-pc.png" class="img-fluid" alt="">
					</div>
					<div class="text-center z-index position-relative home-image animation-bounce" style="position:relative;z-index: 55;top: 50px;";>
						<img src="<?php echo $iniObj->UIPath; ?>/img/hero-mockup.png" class="img-fluid" alt="">
					</div>
				</div>
			</div>
		</div>
		<div class="svg-shape-bottom">
			<img src="<?php echo $iniObj->UIPath; ?>/img/hero-shape-bottom.svg" class="bottom-shape img-fluid" alt="">
		</div>
	</header>
	<!-- End Home Section -->
	
	<!-- Start Features Section -->
	<section id="features" class="features-area section-padding">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 offset-lg-3 col-md-12">
					<div class="section-title">
						<h6 class="small-title">Explore Amazing Features</h6>
						<h2>Appzone Smart Apps Has Lots Of Excellent Features</h2>
					</div>
				</div>
			</div>
			<div class="row d-flex align-items-center">
				<div class="col-lg-4 col-md-6">
					<div class="single-features-item">
						<div class="features-icon color-icon-1"> <i class="ti-settings"></i>
						</div>
						<div class="features-text">
							<h3>Store Optimization</h3>
							<p>Precision haircut, optional hot lather and straight razor neck shave.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="single-features-item">
						<div class="features-icon color-icon-2"> <i class="ti-layout-list-thumb"></i>
						</div>
						<div class="features-text">
							<h3>Notification Snooze</h3>
							<p>Precision haircut, optional hot lather and straight razor neck shave.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="single-features-item">
						<div class="features-icon color-icon-3"> <i class="ti-layout-slider-alt"></i>
						</div>
						<div class="features-text">
							<h3>Adaptive Icons</h3>
							<p>Precision haircut, optional hot lather and straight razor neck shave.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="single-features-item">
						<div class="features-icon color-icon-4"> <i class="ti-layout-accordion-list"></i>
						</div>
						<div class="features-text">
							<h3>Redesigned Settings</h3>
							<p>Precision haircut, optional hot lather and straight razor neck shave.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="single-features-item">
						<div class="features-icon color-icon-5"> <i class="ti-palette"></i>
						</div>
						<div class="features-text">
							<h3>Wide Color Gamut</h3>
							<p>Precision haircut, optional hot lather and straight razor neck shave.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="single-features-item">
						<div class="features-icon color-icon-6"> <i class="ti-shield"></i>
						</div>
						<div class="features-text">
							<h3>Tracking & Monitoring</h3>
							<p>Precision haircut, optional hot lather and straight razor neck shave.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Features Section -->
	
	<!-- Start Counter Section -->
	<section class="counter-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6 counter-item">
					<div class="single-counter">
						<div class="counter-contents">
							<h2>
                                <span class="counter-number">3.7</span>
                                <span>M</span>
                            </h2>
							<h3 class="counter-heading">Apps Download</h3>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 counter-item">
					<div class="single-counter">
						<div class="counter-contents">
							<h2>
                                <span class="counter-number">2.5</span>
                                <span>K</span>
                            </h2>
							<h3 class="counter-heading">Active User</h3>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 counter-item">
					<div class="single-counter">
						<div class="counter-contents">
							<h2>
                                <span class="counter-number">3.5</span>
                                <span>K</span>
                            </h2>
							<h3 class="counter-heading">Happy Client</h3>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 counter-item">
					<div class="single-counter">
						<div class="counter-contents">
							<h2>
                                <span class="counter-number">320</span>
                                <span>+</span>
                            </h2>
							<h3 class="counter-heading">Team Members</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Counter Section -->
	
	<!-- Start About Section -->
	<section id="about" class="about-area section-padding">
		<div class="container">
			<div class="row d-flex align-items-center">
				<div class="col-lg-5 col-md-12">
					<div class="about-info">
						<h6 class="small-title">About The App</h6>
						<h2>Smart App For Easy Life</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
						<ul>
							<li><i class="fa fa-check-circle"></i> Attractive Interface with Many Options</li>
							<li><i class="fa fa-check-circle"></i> Live Chat and Instant Notification</li>
							<li><i class="fa fa-check-circle"></i> Install App with Unlimited Features</li>
						</ul> <a href="#" class="button">Downloade Apps</a>
					</div>
				</div>
				<div class="col-lg-7 col-md-12">
					<div class="about-img">
						<img src="<?php echo $iniObj->UIPath; ?>/img/about.jpg" class="img-fluid" alt="">
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End About Section -->
	
	<!-- Start Video Section -->
	<section class="video-area section-padding">
		<div class="container">
			<div class="row d-flex align-items-center">
				<div class="col-lg-6 col-md-12">
					<div class="video-info">
						<h2>Appzone How it Works?</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
					</div>
				</div>
				<div class="col-lg-6  col-md-12">
					<div class="video-content-popup">
						<a href="https://www.youtube.com/watch?v=HAZiE9NtRfs" class="iq-video popup-video mfp-iframe video-btn"> <i class="fa fa-play-circle"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Video Section -->
	
	<!-- Start Choose Section -->
	<section class="choose-area section-padding">
		<div class="container">
			<div class="row d-flex align-items-center">
				<div class="col-lg-5 col-md-12 col-sm-12">
					<div class="choose-content-images">
						<img src="<?php echo $iniObj->UIPath; ?>/img/choose.png" alt="choose images">
					</div>
				</div>
				<div class="col-lg-6 offset-lg-1 col-md-12 col-sm-12">
					<div class="choose-content">
						<div class="choose-content-info">
							<h6 class="small-title">Why Choose Appzone</h6> 
							<h2>Easy and Perfect Solutions</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud consectetur adipiscing elit.</p>
						</div>
						<div class="choose-feature-box">
							<div class="choose-single-feature">
								<div class="choose-features-icon color-icon-1"><i class="icofont-atom"></i>
								</div>
								<div class="choose-features-info">
									<h3>Our all products are high quality, colorful and fashionable.</h3>
								</div>
							</div>
							<div class="choose-single-feature">
								<div class="choose-features-icon color-icon-2"><i class="icofont-safety"></i>
								</div>
								<div class="choose-features-info">
									<h3>You get full access to your Smart Products where you can change any Content</h3>
								</div>
							</div>
							<div class="choose-single-feature">
								<div class="choose-features-icon color-icon-3"><i class="icofont-headphone"></i>
								</div>
								<div class="choose-features-info">
									<h3>We are providing 24/7 hours dedicated support service for our customers</h3>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Choose Section -->
	
	<!-- Start Screenshort Section -->
	<section id="screenshots" class="screenshort-area pb-100">
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div class="section-title">
						<h6 class="small-title">Latest Short</h6>
						<h2>Beautiful Interface</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="screenshort-slide-content">
						<div class="screenshort-slide owl-carousel owl-theme">
							<div class="screenshort-item">
								<img src="<?php echo $iniObj->UIPath; ?>/img/short/short-1.jpg" class="img-fluid" alt="" />
							</div>
							<div class="screenshort-item">
								<img src="<?php echo $iniObj->UIPath; ?>/img/short/short-2.jpg" class="img-fluid" alt="" />
							</div>
							<div class="screenshort-item">
								<img src="<?php echo $iniObj->UIPath; ?>/img/short/short-3.jpg" class="img-fluid" alt="" />
							</div>
							<div class="screenshort-item">
								<img src="<?php echo $iniObj->UIPath; ?>/img/short/short-4.jpg" class="img-fluid" alt="" />
							</div>
							<div class="screenshort-item">
								<img src="<?php echo $iniObj->UIPath; ?>/img/short/short-5.jpg" class="img-fluid" alt="" />
							</div>
							<div class="screenshort-item">
								<img src="<?php echo $iniObj->UIPath; ?>/img/short/short-6.jpg" class="img-fluid" alt="" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Screenshort Section -->
	
	<!-- Start Testimonials Section -->
	<section id="review" class="testimonial-area position-relative section-padding">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="section-title">
						<h6 class="small-title">Our Client Say</h6>
						<h2>Testimonials</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="testimonial-slide">
						<div class="owl-carousel owl-theme">
							<!-- testimonials item -->
							<div class="single-testimonial">
								<div class="testimonial-content-inner">
									<div class="testimonial-rating">
										<h6>Excellent quality product</h6>
										<ul>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
										</ul>
									</div>
									<div class="testimonial-text">
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
									</div>
									<div class="author-info">
										<div class="author-img">
											<img src="<?php echo $iniObj->UIPath; ?>/img/client/testimonial-1.jpg" alt="testimonial">
										</div>
										<h3>Saabir al-Obeid</h3>
										<span>busniess man</span>
									</div>
								</div>
							</div>
							<!-- testimonials item -->
							<div class="single-testimonial">
								<div class="testimonial-content-inner">
									<div class="testimonial-rating">
										<h6>Excellent quality product</h6>
										<ul>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star-o"></i>
											</li>
										</ul>
									</div>
									<div class="testimonial-text">
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
									</div>
									<div class="author-info">
										<div class="author-img">
											<img src="<?php echo $iniObj->UIPath; ?>/img/client/testimonial-2.jpg" alt="testimonial">
										</div>
										<h3>Ruben Houston</h3>
										<span>busniess man</span>
									</div>
								</div>
							</div>
							<!-- testimonials item -->
							<div class="single-testimonial">
								<div class="testimonial-content-inner">
									<div class="testimonial-rating">
										<h6>Excellent quality product</h6>
										<ul>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
										</ul>
									</div>
									<div class="testimonial-text">
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
									</div>
									<div class="author-info">
										<div class="author-img">
											<img src="<?php echo $iniObj->UIPath; ?>/img/client/testimonial-3.jpg" alt="testimonial">
										</div>
										<h3>Rose Hopkins</h3>
										<span>busniess man</span>
									</div>
								</div>
							</div>
							<!-- testimonials item -->
							<div class="single-testimonial">
								<div class="testimonial-content-inner">
									<div class="testimonial-rating">
										<h6>Excellent quality product</h6>
										<ul>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
											<li><i class="fa fa-star"></i>
											</li>
										</ul>
									</div>
									<div class="testimonial-text">
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
									</div>
									<div class="author-info">
										<div class="author-img">
											<img src="<?php echo $iniObj->UIPath; ?>/img/client/testimonial-4.jpg" alt="testimonial">
										</div>
										<h3>Monica Frazier</h3>
										<span>busniess man</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Testimonials Section -->
	
	<!-- Start Faq Section -->
	<section id="faq" class="faq-area section-padding">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="section-title">
						<h6 class="small-title">Help of the following FAQs</h6>
						<h2>Frequently Asked Questions</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-7 col-md-12">
					<div class="faq-accordion first-faq">
						<ul class="accordion">
							<li class="accordion-item">
								<a class="accordion-title active" href="javascript:void(0)"> <i class="fa fa-caret-down"></i> What do I do when my computer crashes?</a>
								<p class="accordion-content show">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate</p>
							</li>
							<li class="accordion-item">
								<a class="accordion-title" href="javascript:void(0)"> <i class="fa fa-caret-down"></i> There is no display on the monitor, what do I do now?</a>
								<p class="accordion-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa officia deserunt mollit anim id est laborum.</p>
							</li>
							<li class="accordion-item">
								<a class="accordion-title" href="javascript:void(0)"> <i class="fa fa-caret-down"></i> How can I clean my keyboard?</a>
								<p class="accordion-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa officia deserunt mollit anim id est laborum.</p>
							</li>
							<li class="accordion-item">
								<a class="accordion-title" href="javascript:void(0)"> <i class="fa fa-caret-down"></i> Why is my computer mouse acting erratically?</a>
								<p class="accordion-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa officia deserunt mollit anim id est laborum.</p>
							</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-5 col-md-12 faq-item">
					<div class="faq-img animation-bounce">
						<img src="<?php echo $iniObj->UIPath; ?>/img/faq.png" class="img-fluid" alt="faq">
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Faq Section -->
	
	<!-- Start Team Section -->
	<section class="team-area pb-100">
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div class="section-title">
						<h6 class="small-title">Our Leadership</h6>
						<h2>Team Members</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="single-team-box">
						<div class="team-image">
							<img src="assets/img/team/team-1.jpg" alt="team" />
							<div class="team-social-box">
								<div class="team-social-icon">	<a href="#" class="social-color-1"><i class="fa fa-facebook-f"></i></a>
									<a href="#" class="social-color-2"><i class="fa fa-twitter"></i></a>
									<a href="#" class="social-color-3"><i class="fa fa-linkedin"></i></a>
								</div>
							</div>
						</div>
						<div class="team-info">
							<h3>Howard Berry</h3>
							<span>Executive Officer</span>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="single-team-box">
						<div class="team-image">
							<img src="assets/img/team/team-2.jpg" alt="team" />
							<div class="team-social-box">
								<div class="team-social-icon">	<a href="#" class="social-color-1"><i class="fa fa-facebook-f"></i></a>
									<a href="#" class="social-color-2"><i class="fa fa-twitter"></i></a>
									<a href="#" class="social-color-3"><i class="fa fa-linkedin"></i></a>
								</div>
							</div>
						</div>
						<div class="team-info">
							<h3>Morris Nelson</h3>
							<span>Staffing Director</span>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="single-team-box">
						<div class="team-image">
							<img src="<?php echo $iniObj->UIPath; ?>/img/team/team-3.jpg" alt="team" />
							<div class="team-social-box">
								<div class="team-social-icon">	<a href="#" class="social-color-1"><i class="fa fa-facebook-f"></i></a>
									<a href="#" class="social-color-2"><i class="fa fa-twitter"></i></a>
									<a href="#" class="social-color-3"><i class="fa fa-linkedin"></i></a>
								</div>
							</div>
						</div>
						<div class="team-info">
							<h3>Travis Wallace</h3>
							<span>Content Executive</span>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="single-team-box">
						<div class="team-image">
							<img src="assets/img/team/team-4.jpg" alt="team" />
							<div class="team-social-box">
								<div class="team-social-icon">	<a href="#" class="social-color-1"><i class="fa fa-facebook-f"></i></a>
									<a href="#" class="social-color-2"><i class="fa fa-twitter"></i></a>
									<a href="#" class="social-color-3"><i class="fa fa-linkedin"></i></a>
								</div>
							</div>
						</div>
						<div class="team-info">
							<h3>Steve Frazier</h3>
							<span>Technical Executive</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Team Section -->
	
	<!-- Start Download Section -->
	<section id="download" class="download-area">
		<div class="container">
			<div class="row d-flex align-items-center">
				<div class="col-lg-8 offset-lg-2 col-md-12 col-sm-12">
					<div class="download-app-text">
						<h5>Also Available in</h5>
						<h2>Free Download The Appzone Apps Now!</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
						<div class="download-button-wrapper">
							<ul class="inline-btn">
								<li class="list-inline-btn">
									<a href="#" class="d-flex align-items-center button download-btn btn-1">	<span class="fa fa-apple"></span>
										<div class="download-text">	<small>Download On</small>
											<h6>App Store</h6>
										</div>
									</a>
								</li>
								<li class="list-inline-btn">
									<a href="#" class="d-flex align-items-center button download-btn">	<span class="fa fa-android"></span>
										<div class="download-text">	<small>Download form</small>
											<h6>Google Play</h6>
										</div>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Download Section -->
	
	<!-- Start Contact Section -->
	<section id="contact" class="contact-area section-padding">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="section-title">
						<h6 class="small-title">Get In Touch</h6>
						<h2>Contact Us</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-5 col-md-12">
					<div class="contact-information-box-3">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12">
								<div class="single-contact-info-box">
									<div class="contact-info">	<i class="icofont-location-pin"></i>
										<h6>Address:</h6>
										<p>526 Melrose Street,</p>
										<p>Water Mill, 11976 New York.</p>
									</div>
									<div class="contact-info-bg-icon">	<i class="icofont-location-pin"></i>
									</div>
								</div>
							</div>
							<div class="col-lg-12 col-md-12 col-sm-12">
								<div class="single-contact-info-box">
									<div class="contact-info">	<i class="icofont-phone-circle"></i>
										<h6>Phone:</h6>
										<p>+080 707 555-321</p>
										<p>+105 773 321 7775</p>
									</div>
									<div class="contact-info-bg-icon">	<i class="icofont-phone-circle"></i>
									</div>
								</div>
							</div>
							<div class="col-lg-12 col-md-12 col-sm-12">
								<div class="single-contact-info-box">
									<div class="contact-info">	<i class="icofont-email"></i>
										<h6>Email:</h6>
										<p>info@example.com</p>
										<p>support@example.com</p>
									</div>
									<div class="contact-info-bg-icon">	<i class="icofont-email"></i>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-7 col-md-12">
					<p class="form-message"></p>
					<div class="contact-form-box">
						<form class="contact-form form" id="contact-form" action="https://www.webtechnologybd.com/html/appzone/mail.php" method="POST">
							<div class="controls">
								<div class="row">
									<div class="col-lg-12 col-md-12">
										<div class="form-group has-error has-danger">
											<input id="form_name" type="text" name="name" placeholder="Your Name" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-12">
										<div class="form-group has-error has-danger">
											<input id="form_email" type="email" name="email" placeholder="Your Email" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-12">
										<div class="form-group has-error has-danger">
											<input id="form_subject" type="text" name="subject" placeholder="Your Subject" required="required">
										</div>
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<textarea id="form_message" name="message" placeholder="Your Message" rows="4" required="required"></textarea>
										</div>
									</div>
									<div class="col-md-12">
										<button type="submit" class="button">Send Message</button>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Contact Section -->
	
	<!-- Start Footer Section -->
	<footer class="footer-area">
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 130">
			<path fill="#fff" fill-opacity="1" d="M0,64L48,64C96,64,192,64,288,53.3C384,43,480,21,576,37.3C672,53,768,107,864,117.3C960,128,1056,96,1152,80C1248,64,1344,64,1392,64L1440,64L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"></path>
		</svg>
		<div class="footer-top-area">
			<div class="container">
				<div class="row">
					<div class="col-lg-8 offset-lg-2 col-md-12 text-center">
						<div class="footer-logo-box">
							<h2>Appzone Apps</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
						</div>
						<div class="footer-social-icon">
							<a href="#" class="icon"> <i class="fa fa-facebook"></i> 
							</a>
							<a href="#" class="icon"> <i class="fa fa-twitter"></i> 
							</a>
							<a href="#" class="icon"> <i class="fa fa-dribbble"></i> 
							</a>
							<a href="#" class="icon"> <i class="fa fa-behance"></i> 
							</a>
						</div>
						<div class="subscribe-form-box">
							<form>
								<input type="Email" name="email" placeholder="Type Your Email">	<a href="#" class="subscribe-btn">Subscribe</a>
							</form>
						</div>
						<div class="download-app-button">
							<a href="#0" class="img-app-btn-1">
								<img src="assets/img/google-btn.png" class="img-fluid" alt="">
							</a>
							<a href="#0" class="img-app-btn-2">
								<img src="assets/img/apple-btn.png" class="img-fluid" alt="">
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="copyright-area text-center">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p>Copyright &copy; 2021 - All Right Reserved.</p>
						<p>Designed by Cute Themes.</p>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- End Footer Section -->
	
	<!-- Back to Top -->
	<a href="#" class="back-to-top back-to-top-pulse"><i class="fa fa-caret-up"></i></a>
	
	<!-- All Jquery Js-->
	<script src="<?php echo $iniObj->UIPath; ?>/js/jquery-3.5.1.min.js"></script>
	<script src="<?php echo $iniObj->UIPath; ?>/js/bootstrap.min.js"></script>
	<script src="<?php echo $iniObj->UIPath; ?>/js/plugins.js"></script>
	<!--Site Main js-->
	<script src="<?php echo $iniObj->UIPath; ?>/js/mains.js"></script>
</body>


</html>