<main>
            <h2 class="main-title">Tableau de bord</h2>
            <div class="main-cards">
            <div class="main-info">
                    <div class="card-single card-single-body pd-top-bottom-10">
                        <div class="card-single-header padding-10" style="box-shadow:none">
                            <div>
                                <img class="img-gsm" src="<?php $lib->customerSite ?>/UIResources/images/mtn.jpg" alt="" srcset="">
                            </div>
                        </div>
                        
                            <div class="padding-10 padding-top-0">
                                <span><!--<i class="fa fa-mobile orange rem-1-5" style="margin-right: 22px"></i>-->Crédit :</span>
                                <span class="rem-1-5 orange">50000 FCFA</span>
                            </div>
                            <div class="padding-10">
                                <span><!--<i class="fa fa-wallet orange rem-1-5" style="margin-right: 10px"></i>-->Mobile money :</span>
                                <span class="rem-1-5 orange">50000 FCFA</span>
                            </div>
                        
                        
                    </div>
                    <div class="card-single card-single-body pd-top-bottom-10">
                        <div class="card-single-header padding-10" style="box-shadow:none">
                            <div>
                                <img class="img-gsm" src="<?php $lib->customerSite ?>/UIResources/images/moov.png" alt="" srcset="">
                            </div>
                        </div>
                        
                            <div class="padding-10 padding-top-0">
                                <span><!--<i class="fa fa-mobile orange rem-1-5" style="margin-right: 22px"></i>-->Crédit :</span>
                                <span class="rem-1-5 orange">50000 FCFA</span>
                            </div>
                            <div class="padding-10">
                                <span><!--<i class="fa fa-wallet orange rem-1-5" style="margin-right: 10px"></i>-->Mobile money :</span>
                                <span class="rem-1-5 orange">50000 FCFA</span>
                            </div>
                        
                    </div>
                </div>
                <div class="card-single">
                    <div class="card-single-header" style="align-items: center;">
                        <span>Les dernières transactions</span>
                        <a href="<?php $lib->customerSite ?>/operation/historique" class="btn btn-orange">Voir plus</a>
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table table-striped" style="margin-bottom:0">
                            <thead class="">
                                <tr>
                                    <th scope="col" class="primary">Opérations</th>
                                    <th scope="col" class="primary">Dates</th>
                                    <th scope="col" class="primary">Montants</th>
                                    <th scope="col" class="primary">Gsm</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php if(isset($data['operations'])): ?>
                                    <?php foreach($data['operations'] as $operation): ?>
                                        <tr>
                                            <td scope="row"><?=$operation['libelle'] ?></td>
                                            <td><?=$operation['operation_date'] ?></td>
                                            <td><?=$operation['descriptions'] ?></td>
                                            <td>MTN</td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="4">
                                            Pas de données
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                
                <!--<div class="card-single">
                    <div class="card-single-header">
                        <span>MOOV Africa</span>
                        <span class="fa fa-credit-card"></span>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead class="table-bleu">
                                <th class="white">Crédit vendu</th>
                                <th class="white">Mobile money</th>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>50000 FCFA</td>
                                    <td>100000 FCFA</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <a href="/pages/reservation.html">Voir tous</a>
                    </div>
                </div>-->
                <!--<div class="card-single">
                    <div class="card-single-header">
                        <span>MTN</span>
                        <span class="fa fa-credit-card"></span>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead class="table-bleu">
                                <th class="white">Crédit vendu</th>
                                <th class="white">Mobile money</th>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>30000 FCFA</td>
                                    <td>150000 FCFA</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <!--<div class="card-footer">
                        <a href="">Voir tous</a>
                    </div>
                </div>-->
                
            </div>
            <section class="recent">
                <div class="activity-grid">
                    <div class="activity-card">
                        <div class="card-single-header padding-10">
                            <span>Transactions</span>
                        </div>
                        <div>
                            <canvas id="myChart" width="500" height="400"></canvas>
                        </div>
                        
                        <!--<div id="chartContainer2" style="height: 370px; max-width: 920px; margin: 0px auto;"></div> -->
                    </div>
                    <div class="activity-card"> 
                        <div class="card-single-header padding-10">
                            <span>Opérations</span>
                        </div>
                        <div>
                            <canvas id="myChart2" width="400" height="400"></canvas>
                        </div>
                            <!--<div id="chartContainer" style="height: 370px; max-width: 920px; margin: 0px auto;"></div>-->
                    </div>
                </div>
            </section>
        </main>