<main>
    
            <h2 class="main-title">Details</h2>
            <div class="track padding-bottom-20">
                <span <?php if($page_requested =="configurations"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $param2[0];?></span>
            </div>
            <!-- <div class="main-btn">
                <a href="addLicence" id="myBtn"><i class="fas fa-plus" style="margin-right:15px ;"></i>Ajouter une nouvelle licence</a>
            </div> -->
           
            <section class="recent">
                <div class="activity">
                    <div style="padding-top: 5px;" class="activity-card">
                        <h3>Details Inventaire</h3>
                        <div class="table-responsive">
                         
                            <table id="tables" style="margin-top: 30px;" border="0">
                            <thead>
                                    <tr>
                                        <th>Montant de début</th>
                                        <th>Montant fin</th>
                                        <th>Montant de vente</th>
                                        <th>Nombre de transaction</th>
                                        <!-- <th style="text-align:center">Actions</th> -->
                                    </tr>
                                </thead>
                                <tbody>
                              
                                </tbody>
                            </table>                       
                        </div>   
                    </div>
                </div>
                         
            </section>
        </main>