<main>
    
            <h2 class="main-title">Details</h2>
            <div class="track padding-bottom-20">
                <span <?php if($page_requested =="configurations"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $param2[0];?></span>
            </div>
           
            <section class="recent">
                <div class="activity">
                    <div style="padding-top: 5px;" class="activity-card">
                        <h3>Details de <?=$url_array[5] ?> </h3>
                        <div class="table-responsive">
                         
                            <table id="tables" style="margin-top: 30px;" border="0">
                            <thead>
                                    <tr>
                                        <th>Montant de début</th>
                                        <th>Montant de fin</th>
                                        <th>Montant de vente</th>
                                        <th>Nombre de transaction</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php if(isset($response)): ?>
                                        <?php foreach($response as $res): ?>
                                        <tr>
                                             <td><?=$res['balance_start'] ?></td>
                                             <td><?=$res['balance_end'] ?></td>
                                             <td><?=$res['sales_amount'] ?></td>
                                             <td><?=$res['nb_transactions'] ?></td>            
                                        </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>                       
                        </div>   
                    </div>
                </div>
                         
            </section>
        </main>