<main>
    
            <h2 class="main-title">Inventaires</h2>
            <div class="track padding-bottom-20">
                <span <?php if($page_requested =="configurations"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $param2[0];?></span>
            </div>
            <!-- <div class="main-btn">
                <a href="addLicence" id="myBtn"><i class="fas fa-plus" style="margin-right:15px ;"></i>Ajouter une nouvelle licence</a>
            </div> -->
           
            <section class="recent">
                <div class="activity">
                    <div style="padding-top: 5px;" class="activity-card">
                        <h3>Inventaires</h3>
                        <div class="table-responsive">
                         
                            <table id="table" style="margin-top: 30px;" border="0">
                            <thead>
                                    <tr>
                                        <th>Nom de l'inventaire</th>
                                        <th>Date début </th>
                                        <th>Date fin</th>
                                        <th style="text-align:center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php if(isset($response)): ?>
                                        <?php foreach($response as $res): ?>
                                        <tr>
                                             <td><?=$res['inventory_name'] ?></td>
                                             <td><?=$res['date_from'] ?></td>
                                             <td><?=$res['date_to'] ?></td>           
                                             <td style="text-align:center"> 
                                               
                                                <span onclick="document.location='<?php $lib->customerSite ?>/administration/inventaire/details/<?=$res['inventory_id'] ?>/<?=$res['inventory_name'] ?>'" class="cursor btn-action white pg-5 primary">Details</span>

                                             </td>
                                            
                                        </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>                       
                        </div>   
                    </div>
                </div>

            </section>
        </main>